// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcq6_LEpHMgI4QYcgIxPCH337QXeQStdY',
    appId: '1:827212806199:web:0317a573eb98065aa9a7b2',
    messagingSenderId: '827212806199',
    projectId: 'flutterproject01djm',
    authDomain: 'flutterproject01djm.firebaseapp.com',
    storageBucket: 'flutterproject01djm.firebasestorage.app',
    measurementId: 'G-7RT74GK4Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPQnayeoWmGd2JPCJG27tzUmLYTwD8O9o',
    appId: '1:827212806199:android:691dcfa46478354da9a7b2',
    messagingSenderId: '827212806199',
    projectId: 'flutterproject01djm',
    storageBucket: 'flutterproject01djm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'flutterproject01djm',
    authDomain: 'flutterproject01djm.firebaseapp.com',
    storageBucket: 'flutterproject01djm.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'flutterproject01djm',
    authDomain: 'flutterproject01djm.firebaseapp.com',
    storageBucket: 'flutterproject01djm.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcq6_LEpHMgI4QYcgIxPCH337QXeQStdY',
    appId: '1:827212806199:web:78edc8ed238a2ba8a9a7b2',
    messagingSenderId: '827212806199',
    projectId: 'flutterproject01djm',
    authDomain: 'flutterproject01djm.firebaseapp.com',
    storageBucket: 'flutterproject01djm.firebasestorage.app',
    measurementId: 'G-22J0SDWVX9',
  );

}